// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package schema

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for FileDtoStatus.
const (
	DELETED FileDtoStatus = "DELETED"
	EXISTS  FileDtoStatus = "EXISTS"
	TRASHED FileDtoStatus = "TRASHED"
)

// CreateFileDto defines model for CreateFileDto.
type CreateFileDto struct {
	// Bucket The bucket where the file is stored
	Bucket string `json:"bucket"`

	// CreationTime The creation time of the file (optional)
	CreationTime *time.Time `json:"creationTime,omitempty"`

	// Date The date associated with the file (optional)
	Date *time.Time `json:"date,omitempty"`

	// EncryptVersion The encryption version used for the file
	EncryptVersion string `json:"encryptVersion"`

	// FileId The ID of the file (required when size > 0, must not be provided when size = 0)
	FileId *string `json:"fileId,omitempty"`

	// FolderUuid The UUID of the folder containing the file
	FolderUuid openapi_types.UUID `json:"folderUuid"`

	// ModificationTime The last modification time of the file (optional)
	ModificationTime *time.Time `json:"modificationTime,omitempty"`

	// PlainName The plain text name of the file
	PlainName string `json:"plainName"`

	// Size The size of the file in bytes
	Size float32 `json:"size"`

	// Type The type of the file (optional)
	Type *string `json:"type,omitempty"`
}

// FileDto defines model for FileDto.
type FileDto struct {
	Bucket           string        `json:"bucket"`
	CreatedAt        time.Time     `json:"createdAt"`
	CreationTime     time.Time     `json:"creationTime"`
	EncryptVersion   string        `json:"encryptVersion"`
	FileId           *string       `json:"fileId"`
	FolderId         float32       `json:"folderId"`
	FolderUuid       string        `json:"folderUuid"`
	Id               float32       `json:"id"`
	ModificationTime time.Time     `json:"modificationTime"`
	Name             string        `json:"name"`
	PlainName        string        `json:"plainName"`
	Size             string        `json:"size"`
	Status           FileDtoStatus `json:"status"`
	Type             string        `json:"type"`
	UpdatedAt        time.Time     `json:"updatedAt"`
	UserId           float32       `json:"userId"`
	Uuid             string        `json:"uuid"`
}

// FileDtoStatus defines model for FileDto.Status.
type FileDtoStatus string

// GetUserUsageDto defines model for GetUserUsageDto.
type GetUserUsageDto struct {
	Backup float32 `json:"backup"`
	Drive  float32 `json:"drive"`
	Total  float32 `json:"total"`
}

// FileControllerCreateFileJSONRequestBody defines body for FileControllerCreateFile for application/json ContentType.
type FileControllerCreateFileJSONRequestBody = CreateFileDto

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// FileControllerCreateFileWithBody request with any body
	FileControllerCreateFileWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	FileControllerCreateFile(ctx context.Context, body FileControllerCreateFileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UserControllerGetUserUsage request
	UserControllerGetUserUsage(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) FileControllerCreateFileWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFileControllerCreateFileRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FileControllerCreateFile(ctx context.Context, body FileControllerCreateFileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFileControllerCreateFileRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UserControllerGetUserUsage(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUserControllerGetUserUsageRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewFileControllerCreateFileRequest calls the generic FileControllerCreateFile builder with application/json body
func NewFileControllerCreateFileRequest(server string, body FileControllerCreateFileJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFileControllerCreateFileRequestWithBody(server, "application/json", bodyReader)
}

// NewFileControllerCreateFileRequestWithBody generates requests for FileControllerCreateFile with any type of body
func NewFileControllerCreateFileRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/files")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUserControllerGetUserUsageRequest generates requests for UserControllerGetUserUsage
func NewUserControllerGetUserUsageRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/usage")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// FileControllerCreateFileWithBodyWithResponse request with any body
	FileControllerCreateFileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FileControllerCreateFileResponse, error)

	FileControllerCreateFileWithResponse(ctx context.Context, body FileControllerCreateFileJSONRequestBody, reqEditors ...RequestEditorFn) (*FileControllerCreateFileResponse, error)

	// UserControllerGetUserUsageWithResponse request
	UserControllerGetUserUsageWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*UserControllerGetUserUsageResponse, error)
}

type FileControllerCreateFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FileDto
}

// Status returns HTTPResponse.Status
func (r FileControllerCreateFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FileControllerCreateFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UserControllerGetUserUsageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetUserUsageDto
}

// Status returns HTTPResponse.Status
func (r UserControllerGetUserUsageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UserControllerGetUserUsageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// FileControllerCreateFileWithBodyWithResponse request with arbitrary body returning *FileControllerCreateFileResponse
func (c *ClientWithResponses) FileControllerCreateFileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FileControllerCreateFileResponse, error) {
	rsp, err := c.FileControllerCreateFileWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFileControllerCreateFileResponse(rsp)
}

func (c *ClientWithResponses) FileControllerCreateFileWithResponse(ctx context.Context, body FileControllerCreateFileJSONRequestBody, reqEditors ...RequestEditorFn) (*FileControllerCreateFileResponse, error) {
	rsp, err := c.FileControllerCreateFile(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFileControllerCreateFileResponse(rsp)
}

// UserControllerGetUserUsageWithResponse request returning *UserControllerGetUserUsageResponse
func (c *ClientWithResponses) UserControllerGetUserUsageWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*UserControllerGetUserUsageResponse, error) {
	rsp, err := c.UserControllerGetUserUsage(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUserControllerGetUserUsageResponse(rsp)
}

// ParseFileControllerCreateFileResponse parses an HTTP response from a FileControllerCreateFileWithResponse call
func ParseFileControllerCreateFileResponse(rsp *http.Response) (*FileControllerCreateFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FileControllerCreateFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FileDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUserControllerGetUserUsageResponse parses an HTTP response from a UserControllerGetUserUsageWithResponse call
func ParseUserControllerGetUserUsageResponse(rsp *http.Response) (*UserControllerGetUserUsageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UserControllerGetUserUsageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetUserUsageDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
